# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='200x200 pixels image', null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
